version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '11:00'
      timezone: America/Sao_Paulo
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 10
    reviewers:
      - julianosbento
      - LopesAlysson
      - pedro-cerdera
      - lucianomlima
      - albertozaranza
      - Michele-Camargo
    ignore:
      - dependency-name: '@babel/runtime'
      - dependency-name: '@babel/core'
      - dependency-name: 'react'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'react-native'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
