version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '08:00'
      timezone: America/Sao_Paulo
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 6
    reviewers:
      - 'magnetis/frontend'
    target-branch: 'main'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '08:00'
      timezone: America/Sao_Paulo
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 6
    reviewers:
      - 'magnetis/frontend'
    target-branch: 'astro-native@next'
